### ISSUE TITLE
 Design Goals

### ISSUE THREAD

**Issue by Jammyjamjamman** [theimpossibleastronaut/energy-calculator#3]
Currently, the main purpose of this project is to learn about coding in Rust. But, we also want to make a program which demonstrates the mass-energy relationship. These are the physics concepts we want the project to demonstrate:

1. Demonstrate E = mc² . This just simply means show that mass is directly proportional to energy (i.e. as mass increases, energy increases). This should also show that energy and mass should **NOT** be negative.

2. Talk about an application of this relationship. This is difficult because I can only think of 2 areas where this is important; nuclear reactions (fission and fusion) and "radiation pressure". I think we should cover nuclear reactions at least. The next goals therefore follow.

3. Talk about the [binding energy per nucleon](https://en.wikipedia.org/wiki/Nuclear_binding_energy). (The most atomically stable element is Iron.)

3. Show that [nuclear fusion](https://en.wikipedia.org/wiki/Nuclear_fusion) reactions produce energy by converting mass into energy. This is because the "binding energy per nucleon" increases when e.g. hydrogen is converted into helium. This binding energy seen as a the protons an neutrons losing mass.

4. Show that [nuclear fission](https://en.wikipedia.org/wiki/Nuclear_fission) reactions produce energy (for more-or less the same reasons given above, but the reactions are a bit more complex).

The project will also require a small structure and maybe a GUI interface. A coding style will also need developing as early as possible (as in, rust supports a number of [paradigms](https://en.wikipedia.org/wiki/Programming_paradigm).

This post addresses #1

**Comment by andy5995** [comment]
It's good to have structure :) Sounds like you already have something in mind, and will structure it as more code is added?

**Comment by Jammyjamjamman** [comment]
>  Sounds like you already have something in mind, and will structure it as more code is added?

There's some structure I would like to implement immediately, but more structure can be added later as needed. As long as the code is modularised, there shouldn't be a problem.

**Comment by andy5995** [comment]
I think all this info was added to the README in https://github.com/theimpossibleastronaut/energy-calculator/commit/532bc908ef192adb91c45ea0d7ba8bfb0681983f
