### ISSUE TITLE
Program specification

### ISSUE THREAD

**Issue by Jammyjamjamman** [theimpossibleastronaut/energy-calculator#5]
A more thorough spec for what the program should do needs writing. For now, the program should: 

* Give textual information to the user, which talks about concepts when using energy-mass calculations.

* Calculate the energy produces when e.g. hydrogen is used to produce helium.

**Comment by andy5995** [comment]
Do you think the spec should be in the README or a separate spec file?

**Comment by Jammyjamjamman** [comment]
Maybe just in the README for now. It can be moved to a separate file later. (Although, setting up a separate file wouldn't be difficult).

**Comment by andy5995** [comment]
Closed by https://github.com/theimpossibleastronaut/energy-calculator/commit/532bc908ef192adb91c45ea0d7ba8bfb0681983f
