### ISSUE TITLE
Add more unit conversions.

### ISSUE THREAD

**Issue by Jammyjamjamman** [theimpossibleastronaut/energy-calculator#9]
Some unit conversions have been added (see src/physics/converter.rs). However, some more could be added:

* kg to pounds (easy)
* metres to feet (easy)
* Kelvin to Fahrenheit (fairly easy)
* Newtons to pounds (hard)
* Torque from Nm to pound-feet (hard)
* Energy from Joules (J) to electron volts (eV) (easy but will require some research to understand). This one is important for the energy calculator.

Feel free to implement other conversions, apart from/ as well as these.

Some rules:
* Implement in src/physics/converter.rs
* Unit types are defined as simple tuple structs.
* Converters should used some functions defined earlier on. These functions convert **S.I. units only** to any other unit.
* Implementations of converters are done using the `From` trait.

If a better solution for implementing this than the rules given above is possible, go for it!

**Comment by andy5995** [comment]
Taking an extended break from coding. andy5995 is going into maintenance mode.

**Comment by Jammyjamjamman** [comment]
I'm gonna need more time as well to get my rust knowledge up to speed.
